name: Build, Lint, and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore: []

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        no-fail: true
      
    - name: Build Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        tags: snakemake-tutorial
        outputs: type=docker, dest=/tmp/snakemake-tutorial.tar

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with: 
        name: snakemake-tutorial
        path: /tmp/snakemake-tutorial.tar

  lint:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint Snakefile
        uses: github/super-linter@v7
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          VALIDATE_SNAKEMAKE_SNAKEFMT: true

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: snakemake-tutorial
          path: /tmp/snakemake-tutorial.tar

      - name: Load Docker Image
        run: docker load -i /tmp/snakemake-tutorial.tar

      - name: DryRun Snakefile
        run: docker run snakemake/snakemake-tutorial snakemake --cores 1 --dryrun

  test:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: snakemake-tutorial
          path: /tmp/snakemake-tutorial.tar

      - name: Load Docker Image
        run: docker load -i /tmp/snakemake-tutorial.tar

      - name: Run Tests
        run: docker run snakemake-tutorial snakemake --cores 1 
