name: Build, Lint, and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore: []

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        no-fail: true
      
    - name: Build Docker Image
      run: docker build -t snakemake-tutorial .

  lint:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Snakefile
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          VALIDATE_SNAKEMAKE_SNAKEFMT: true

      - name: DryRun Snakefile
        run: docker run snakemake-tutorial snakemake --cores 1 --dryrun

  test:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Tests
        run: docker run snakemake-tutorial snakemake --cores 1 